name: LarkRobot

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      name:
        description: "手动触发构建"
        required: true
        default: "手动触发"

env:
  IMAGE_NAME: kevinmatt/larkbot_v2
  ROBOT_NAME: LarkRobotV2

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - name: Calculate timestamp
        id: timestamp
        run: echo "timestamp=$(date +%s%3N)" >> $GITHUB_OUTPUT

  PushToDockerHub:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: kevinmatt
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: scripts/larkrobot/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:latest-${{ needs.prepare.outputs.timestamp }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

  Notify:
    if: github.event_name != 'pull_request'
    needs: [PushToDockerHub] # 保持不变，仍然依赖 DockerHub 推送
    runs-on: ubuntu-latest
    steps:
      - name: Gotify Notification
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: "${{ secrets.GOTIFY_URL }}"
          gotify_app_token: "${{ secrets.GOTIFY_APP_TOKEN }}"
          notification_title: "${{ env.ROBOT_NAME }} Build Complete"
          notification_message: "Your build was completed. Image: ${{ env.IMAGE_NAME }}:latest-${{ needs.prepare.outputs.timestamp }}"
